server:
  port: 6060

seata:
  application-id: ${spring.application.name:}
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  registry:
    type: file
  data-source-proxy-mode: AT
spring:
  application:
    name: seata-at-provider-business-example