package xyz.wochib70.exam.domain.question;

public enum RenderType {

    SINGLE_ANSWER_MULTIPLE_CHOICE,

    MATERIAL_SINGLE_ANSWER_MULTIPLE_CHOICE,

    MULTIPLE_ANSWER_MULTIPLE_CHOICE,

    MATERIAL_MULTIPLE_ANSWER_MULTIPLE_CHOICE,

    ORDINARY_FILL_BLANK;

}
