spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/jimmer_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: error
logging:
  level:
    root: info
    org:
      babyfish:
        jimmer:
          sql: debug